### ISSUE TITLE
Instructions for Eclipse IDE Beginners

### ISSUE THREAD

**Issue by Pelotes72** [rolandweber/pityoulish#71]
Fur future reference:
# Instructions for Eclipse IDE Beginners
## Import jar 

1. Create new, empty Java Project (`File > New > Java Project`) with default settings
2. Unfold the created project in Package Explorer
3. Right click on the `src` folder and choose `Import...`
4. Select `General > Archive File` and on the next screen, select the appropriate jar file.
5. Finish.

## Run with cmd arguments

1. Click on the down arrow next to `Run` (arrow in green circle), or open `Run` menu.
2. Choose `Run As > Java Application`.
3. The project will be run without arguments and should show inline usage instructions in the Console.
4. Open `Run` dropdown again and choose `Run Configurations...`
5. Choose the config that was created (if not already selected) and switch to the `Arguments` tab to edit the `Program Arguments`.
6. Run.

Alternatively, you could export the jar and run it from your OS command line.

## Export jar

1. Choose `File > Export... > Java > Runnable JAR file...`
2. Choose the Launch configuration that you created before and set the Export destination.
3. Finish.

**Comment by rolandweber** [comment]
@Pelotes72: Thanks a lot!
